import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  bool get isPersian => locale.languageCode == 'fa';

  static const supportedLocales = <Locale>[
    Locale('fa', 'IR'),
    Locale('en', 'US'),
  ];

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  @visibleForTesting
  static Set<String> translationKeysFor(Locale locale) =>
      Set<String>.unmodifiable(
        locale.languageCode == 'fa' ? _fa.keys : _en.keys,
      );

  String tr(String key, [Map<String, Object?> values = const {}]) {
    var value = (isPersian ? _fa : _en)[key] ?? _en[key] ?? key;
    for (final entry in values.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value?.toString() ?? '');
    }
    return value;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _Delegate();

  static const _fa = <String, String>{
    'app.name': 'HardwareReserve',
    'nav.home': 'خانه',
    'nav.servers': 'سرورها',
    'nav.reservations': 'رزروها',
    'nav.services': 'سرویس‌ها',
    'nav.profile': 'حساب من',
    'nav.support': 'پشتیبانی',
    'admin.entry.title': 'فضای مدیریت',
    'admin.entry.subtitle': 'مدیریت سرورها، رزروها، کاربران و پشتیبانی',
    'admin.nav.overview': 'نمای کلی',
    'admin.nav.servers': 'سرورها',
    'admin.nav.reservations': 'رزروها',
    'admin.nav.users': 'کاربران',
    'admin.nav.support': 'پشتیبانی',
    'admin.servers.title': 'مدیریت سرورها',
    'admin.servers.inventory': 'فهرست سرورها',
    'admin.servers.search':
        'جست‌وجوی شناسه، CPU، GPU، RAM، فضای ذخیره‌سازی یا سیستم‌عامل',
    'admin.servers.clearSearch': 'پاک‌کردن جست‌وجو',
    'admin.servers.statusFilter': 'وضعیت عملیاتی',
    'admin.servers.allStatuses': 'همه وضعیت‌ها',
    'admin.servers.empty': 'هنوز سروری ساخته نشده است.',
    'admin.servers.noResults': 'سروری با این فیلترها پیدا نشد.',
    'admin.servers.serverNumber': 'سرور شماره {id}',
    'admin.servers.create': 'افزودن سرور',
    'admin.servers.createTitle': 'افزودن سرور',
    'admin.servers.edit': 'ویرایش سرور',
    'admin.servers.editTitle': 'ویرایش سرور',
    'admin.servers.saveChanges': 'ذخیره تغییرات',
    'admin.servers.hardware': 'مشخصات سخت‌افزاری',
    'admin.servers.storage': 'فضای ذخیره‌سازی',
    'admin.servers.pricing': 'قیمت‌گذاری',
    'admin.servers.pricingHelp':
        'قیمت روزانه باید از قیمت ساعتی بیشتر و حداکثر ۲۴ برابر آن باشد.',
    'admin.servers.hourlyPrice': 'قیمت ساعتی',
    'admin.servers.dailyPrice': 'قیمت روزانه',
    'admin.servers.availability': 'دسترس‌پذیری',
    'admin.servers.activeState': 'سرور فعال',
    'admin.servers.activeHelp':
        'سرور غیرفعال از دید کاربران پنهان است و بازه نگهداری جدید نمی‌پذیرد.',
    'admin.servers.active': 'فعال',
    'admin.servers.inactive': 'غیرفعال',
    'admin.servers.status': 'وضعیت',
    'admin.servers.finderEligible': 'نمایش در پیشنهاد هوشمند',
    'admin.servers.finderHelp':
        'اجازه نمایش این سرور در پیشنهاد هوشمند سخت‌افزار.',
    'admin.servers.capabilities': 'قابلیت‌های مدیریتی',
    'admin.servers.managedConfiguration': 'پیکربندی مدیریتی',
    'admin.servers.performanceTier': 'سطح عملکرد',
    'admin.servers.cpuCapability': 'توان پردازشی CPU',
    'admin.servers.gpuCapability': 'توان پردازشی GPU',
    'admin.servers.workloadCapabilities': 'قابلیت‌های نوع کاربری',
    'admin.servers.workloadHelp':
        'نوع کاربری پشتیبانی‌شده و میزان تناسب آن را از ۱ تا ۵ انتخاب کنید.',
    'admin.servers.suitability': 'سطح',
    'admin.servers.noWorkloads': 'قابلیتی برای نوع کاربری تنظیم نشده است.',
    'admin.servers.yes': 'بله',
    'admin.servers.no': 'خیر',
    'admin.servers.deleteTitle': 'این سرور غیرفعال شود؟',
    'admin.servers.deleteBody':
        'سرور شماره {id} غیرفعال و از دید کاربران پنهان می‌شود؛ سوابق آن حفظ خواهند شد.',
    'admin.servers.disable': 'غیرفعال‌کردن سرور',
    'admin.servers.disabled': 'سرور غیرفعال شد.',
    'admin.servers.notFound': 'سرور پیدا نشد؛ فهرست را به‌روزرسانی کنید.',
    'admin.servers.verifyCreateBeforeRetry':
        'نتیجه درخواست مشخص نیست؛ برای جلوگیری از ساخت سرور تکراری، پیش از ارسال دوباره فهرست را به‌روزرسانی کنید.',
    'admin.servers.status.available': 'آماده رزرو',
    'admin.servers.status.temporarilyUnavailable': 'موقتاً خارج از دسترس',
    'admin.servers.status.maintenance': 'در حال نگهداری',
    'admin.servers.status.disabled': 'غیرفعال',
    'admin.servers.tier.entry': 'پایه',
    'admin.servers.tier.standard': 'استاندارد',
    'admin.servers.tier.high': 'بالا',
    'admin.servers.tier.extreme': 'فوق‌سنگین',
    'admin.servers.workload.modelTraining': 'آموزش مدل',
    'admin.servers.workload.inference': 'استنتاج',
    'admin.servers.workload.rendering': 'رندرینگ',
    'admin.servers.workload.developmentCompilation': 'توسعه و کامپایل',
    'admin.servers.workload.dataProcessing': 'پردازش داده',
    'admin.servers.workload.webBackendHosting': 'میزبانی وب و بک‌اند',
    'admin.servers.workload.generalCompute': 'پردازش عمومی',
    'admin.servers.maintenanceTitle': 'بازه‌های نگهداری',
    'admin.servers.addMaintenance': 'افزودن بازه نگهداری',
    'admin.servers.createMaintenance': 'ثبت بازه نگهداری',
    'admin.servers.maintenanceHelp':
        'یک بازه آینده انتخاب کنید؛ زمان‌ها محلی نمایش داده و با UTC به سرور ارسال می‌شوند.',
    'admin.servers.maintenanceReason': 'دلیل (اختیاری)',
    'admin.servers.maintenanceTimeInvalid':
        'شروع باید در آینده و پایان پس از زمان شروع باشد.',
    'admin.servers.maintenanceConflict':
        'این بازه با رزرو، بازه نگهداری دیگر یا وضعیت عدم‌دسترسی سرور تداخل دارد.',
    'admin.servers.maintenanceCreated': 'بازه نگهداری ثبت شد.',
    'admin.servers.maintenanceRemoved': 'بازه نگهداری حذف شد.',
    'admin.servers.maintenanceEmpty': 'بازه نگهداری ثبت نشده است.',
    'admin.servers.maintenanceInactiveHint':
        'برای سرور غیرفعال نمی‌توان بازه نگهداری جدید ثبت کرد.',
    'admin.servers.maintenanceUpcoming': 'آینده',
    'admin.servers.maintenanceActive': 'در حال اجرا',
    'admin.servers.maintenanceCompleted': 'پایان‌یافته',
    'admin.servers.removeMaintenance': 'حذف بازه نگهداری',
    'admin.servers.removeMaintenanceTitle': 'این بازه نگهداری حذف شود؟',
    'admin.servers.removeMaintenanceBody':
        'با حذف آن، دسترس‌پذیری این بازه همچنان تابع رزروها و وضعیت سرور خواهد بود.',
    'admin.validation.required': 'تکمیل این فیلد الزامی است.',
    'admin.validation.number': 'یک عدد معتبر وارد کنید.',
    'admin.validation.positive': 'عددی بزرگ‌تر از صفر وارد کنید.',
    'admin.validation.backendDetails': 'جزئیات اعتبارسنجی سرور',
    'admin.validation.max100': 'حداکثر ۱۰۰ نویسه وارد کنید.',
    'admin.dashboard.title': 'نمای کلی مدیریت',
    'admin.dashboard.description':
        'وضعیت عملیات، ظرفیت سرورها و درخواست‌های پشتیبانی را در یک نگاه ببینید.',
    'admin.dashboard.totalUsers': 'کل کاربران',
    'admin.dashboard.totalServers': 'کل سرورها',
    'admin.dashboard.totalPurchases': 'پرداخت‌های تکمیل‌شده',
    'admin.dashboard.activeReservations': 'رزروهای فعال',
    'admin.dashboard.upcomingReservations': 'رزروهای آینده',
    'admin.dashboard.startingSoon': 'شروع در آینده نزدیک',
    'admin.dashboard.endingSoon': 'پایان در آینده نزدیک',
    'admin.dashboard.pendingPayments': 'پرداخت‌های در انتظار',
    'admin.dashboard.unavailableServers': 'سرورهای خارج از دسترس',
    'admin.dashboard.maintenanceServers': 'سرورهای در حال نگهداری',
    'admin.dashboard.waitingSupport': 'پشتیبانی در انتظار',
    'admin.dashboard.operations': 'دسترسی سریع',
    'admin.dashboard.serversTitle': 'مدیریت سرورها',
    'admin.dashboard.ordersTitle': 'رزروها و سفارش‌ها',
    'admin.dashboard.usersTitle': 'مدیریت کاربران',
    'admin.dashboard.supportTitle': 'صندوق پشتیبانی',
    'admin.dashboard.pendingAssignmentsBadge': 'سرویس‌های نیازمند تخصیص',
    'admin.dashboard.supportAttentionBadge': 'گفت‌وگوهای نیازمند توجه',
    'admin.dashboard.recentAudit': 'رویدادهای اخیر مدیریتی',
    'admin.pagination.previous': 'صفحه قبل',
    'admin.pagination.next': 'صفحه بعد',
    'admin.pagination.page': 'صفحه {page}',
    'admin.pagination.total': 'از {count} مورد',
    'admin.provisioning.assigned': 'اطلاعات اتصال تخصیص یافته',
    'admin.provisioning.notAssigned': 'تخصیص‌نیافته',
    'admin.reservations.title': 'رزروها و سفارش‌ها',
    'admin.reservations.search': 'جست‌وجو',
    'admin.reservations.searchHint': 'شناسه، کاربر، ایمیل یا سرور',
    'admin.reservations.statusFilter': 'وضعیت رزرو',
    'admin.reservations.assignmentFilter': 'وضعیت تخصیص',
    'admin.reservations.applyFilters': 'اعمال فیلتر',
    'admin.reservations.clearFilters': 'پاک‌کردن فیلترها',
    'admin.reservations.empty': 'رزرویی با این فیلترها پیدا نشد.',
    'admin.reservations.number': 'رزرو شماره {id}',
    'admin.reservations.filter.all': 'همه',
    'admin.reservations.filter.pendingPayment': 'در انتظار پرداخت',
    'admin.reservations.filter.active': 'فعال',
    'admin.reservations.filter.upcoming': 'آینده',
    'admin.reservations.filter.completed': 'پایان‌یافته',
    'admin.reservations.filter.cancelled': 'لغوشده',
    'admin.reservations.assignment.all': 'همه',
    'admin.reservations.assignment.needsAssignment': 'نیازمند تخصیص',
    'admin.reservations.assignment.assigned': 'تخصیص‌یافته',
    'admin.reservationDetail.title': 'رزرو شماره {id}',
    'admin.reservationDetail.customer': 'کاربر',
    'admin.reservationDetail.userName': 'نام',
    'admin.reservationDetail.email': 'ایمیل',
    'admin.reservationDetail.userId': 'شناسه کاربر',
    'admin.reservationDetail.openUser': 'مشاهده حساب کاربر',
    'admin.reservationDetail.hardware': 'سخت‌افزار',
    'admin.reservationDetail.serverId': 'شناسه سرور',
    'admin.reservationDetail.storage': 'فضای ذخیره‌سازی',
    'admin.reservationDetail.schedulePayment': 'زمان‌بندی و پرداخت',
    'admin.reservationDetail.start': 'شروع',
    'admin.reservationDetail.end': 'پایان',
    'admin.reservationDetail.total': 'مبلغ کل',
    'admin.reservationDetail.credentials': 'اطلاعات اتصال',
    'admin.reservationDetail.credentialsHint':
        'اطلاعات را فقط برای رزرو پرداخت‌شده وارد کنید. مقادیر در دستگاه ذخیره نمی‌شوند.',
    'admin.reservationDetail.credentialsReassignHint':
        'این رزرو قبلاً اطلاعات اتصال دارد. ارسال دوباره، مقادیر قبلی را جایگزین می‌کند.',
    'admin.reservationDetail.credentialsUnpaid':
        'تخصیص اطلاعات اتصال فقط پس از پرداخت رزرو امکان‌پذیر است.',
    'admin.reservationDetail.ip': 'آدرس IP',
    'admin.reservationDetail.username': 'نام کاربری',
    'admin.reservationDetail.password': 'رمز عبور',
    'admin.reservationDetail.currentCredentials': 'اطلاعات فعلی سرویس',
    'admin.reservationDetail.revealPassword': 'نمایش رمز عبور',
    'admin.reservationDetail.hidePassword': 'پنهان کردن رمز عبور',
    'admin.reservationDetail.assign': 'تخصیص اطلاعات',
    'admin.reservationDetail.assigning': 'در حال تخصیص…',
    'admin.reservationDetail.assignTitle': 'تخصیص اطلاعات اتصال',
    'admin.reservationDetail.assignConfirm':
        'این اطلاعات برای کاربر قابل مشاهده خواهد شد. از درستی آن‌ها مطمئن هستید؟',
    'admin.reservationDetail.reassign': 'جایگزینی اطلاعات',
    'admin.reservationDetail.reassignTitle': 'جایگزینی اطلاعات اتصال',
    'admin.reservationDetail.reassignConfirm':
        'اطلاعات فعلی جایگزین می‌شود و کاربر فقط مقادیر جدید را می‌بیند. ادامه می‌دهید؟',
    'admin.reservationDetail.assignSuccess':
        'اطلاعات اتصال با موفقیت تخصیص یافت.',
    'admin.reservationDetail.cancel': 'لغو رزرو',
    'admin.reservationDetail.cancelTitle': 'این رزرو لغو شود؟',
    'admin.reservationDetail.cancelConfirm':
        'رزرو لغو می‌شود و این عمل بر دسترس‌پذیری سرور اثر می‌گذارد.',
    'admin.reservationDetail.cancelSuccess': 'رزرو لغو شد.',
    'admin.reservationDetail.cancelInvalid':
        'امکان لغو این رزرو در وضعیت فعلی وجود ندارد.',
    'admin.users.title': 'کاربران',
    'admin.users.search': 'جست‌وجوی کاربر',
    'admin.users.searchPlaceholder': 'نام، ایمیل یا شناسه',
    'admin.users.clearSearch': 'پاک‌کردن جست‌وجو',
    'admin.users.empty': 'کاربری پیدا نشد.',
    'admin.users.accountNumber': 'حساب شماره {id}',
    'admin.users.roleAdmin': 'مدیر',
    'admin.users.roleUser': 'کاربر',
    'admin.users.verified': 'ایمیل تأییدشده',
    'admin.users.unverified': 'ایمیل تأییدنشده',
    'admin.users.createTitle': 'ساخت حساب مدیر',
    'admin.users.createDescription':
        'مدیر جدید با همان نقش و دسترسی‌های فعلی ساخته می‌شود.',
    'admin.users.fullName': 'نام و نام خانوادگی',
    'admin.users.email': 'ایمیل',
    'admin.users.password': 'گذرواژه',
    'admin.users.confirmPassword': 'تکرار گذرواژه',
    'admin.users.passwordPolicy': 'گذرواژه باید بین ۸ تا ۱۲۸ نویسه باشد.',
    'admin.users.passwordMismatch': 'گذرواژه‌ها یکسان نیستند.',
    'admin.users.createAction': 'ساخت مدیر',
    'admin.users.creating': 'در حال ساخت...',
    'admin.users.createSuccess': 'حساب مدیر {email} ساخته شد.',
    'admin.userOverview.title': 'نمای کلی کاربر',
    'admin.userOverview.userId': 'شناسه کاربر',
    'admin.userOverview.createdAt': 'زمان ایجاد حساب',
    'admin.userOverview.emailVerifiedAt': 'زمان تأیید ایمیل',
    'admin.userOverview.metrics': 'خلاصه فعالیت',
    'admin.userOverview.reservations': 'کل رزروها',
    'admin.userOverview.active': 'رزروهای فعال',
    'admin.userOverview.payments': 'پرداخت‌های موفق',
    'admin.userOverview.support': 'گفت‌وگوهای پشتیبانی',
    'admin.userOverview.unread': 'اعلان‌های خوانده‌نشده',
    'admin.userOverview.recentReservations': 'رزروهای اخیر',
    'admin.userOverview.noReservations': 'این کاربر هنوز رزرویی ندارد.',
    'admin.status.reservation.PendingPayment': 'در انتظار پرداخت',
    'admin.status.reservation.Paid': 'پرداخت‌شده',
    'admin.status.reservation.Cancelled': 'لغوشده',
    'admin.status.payment.Unpaid': 'پرداخت‌نشده',
    'admin.status.payment.Pending': 'در انتظار',
    'admin.status.payment.Completed': 'تکمیل‌شده',
    'admin.status.payment.Failed': 'ناموفق',
    'admin.status.payment.Refunded': 'بازپرداخت‌شده',
    'admin.audit.actions.MaintenanceCreated': 'بازه نگهداری ثبت شد',
    'admin.audit.actions.MaintenanceRemoved': 'بازه نگهداری حذف شد',
    'admin.audit.actions.ManualNotificationSent': 'اعلان مستقیم ارسال شد',
    'admin.audit.actions.BroadcastNotificationSent': 'اعلان همگانی ارسال شد',
    'admin.audit.actions.ReservationCancelled': 'رزرو لغو شد',
    'admin.audit.actions.CredentialsAssigned': 'اطلاعات اتصال تخصیص یافت',
    'admin.audit.actions.ServerCreated': 'سرور ایجاد شد',
    'admin.audit.actions.ServerConfigurationChanged': 'پیکربندی سرور تغییر کرد',
    'admin.audit.actions.ServerDisabled': 'سرور غیرفعال شد',
    'admin.audit.actions.AdminAccountCreated': 'حساب مدیر ساخته شد',
    'admin.support.assignment.mine': 'در اختیار من',
    'admin.support.assignment.other': 'در اختیار همکار',
    'admin.support.assignment.otherHint':
        'این گفت‌وگو در اختیار مدیر دیگری است.',
    'admin.support.conversation.aiHandoff': 'خلاصه تحویل از دستیار هوشمند',
    'admin.support.conversation.claim': 'پذیرش و شروع پاسخ‌گویی',
    'admin.support.conversation.claimBeforeReply':
        'پیش از پاسخ‌گویی، گفت‌وگو را بپذیرید.',
    'admin.support.conversation.close': 'بستن گفت‌وگو',
    'admin.support.conversation.closeConfirm':
        'گفت‌وگوی بسته دیگر پیام جدید نمی‌پذیرد.',
    'admin.support.conversation.closeTitle': 'گفت‌وگو بسته شود؟',
    'admin.support.conversation.closedNotice':
        'این گفت‌وگو بسته است و پیام جدید نمی‌پذیرد.',
    'admin.support.conversation.editTitle': 'ویرایش عنوان',
    'admin.support.conversation.noMessages': 'هنوز پیامی در این گفت‌وگو نیست.',
    'admin.support.conversation.olderEvents': 'رویدادهای قدیمی‌تر',
    'admin.support.conversation.olderMessages': 'پیام‌های قدیمی‌تر',
    'admin.support.conversation.resolve': 'حل‌شده',
    'admin.support.conversation.resolveConfirm':
        'وضعیت برای همه شرکت‌کنندگان به حل‌شده تغییر می‌کند.',
    'admin.support.conversation.resolveTitle': 'حل‌شده علامت‌گذاری شود؟',
    'admin.support.conversation.resolvedNotice':
        'گفت‌وگو حل شده است. در صورت نیاز آن را ببندید.',
    'admin.support.conversation.timeline': 'تاریخچه رویدادها',
    'admin.support.conversation.title': 'گفت‌وگوی پشتیبانی',
    'admin.support.conversation.titleField': 'عنوان',
    'admin.support.event.aiEscalated': 'دستیار هوشمند گفت‌وگو را ارجاع داد',
    'admin.support.event.aiFailed': 'پردازش دستیار هوشمند ناموفق بود',
    'admin.support.event.claimed': 'گفت‌وگو پذیرفته شد',
    'admin.support.event.closed': 'گفت‌وگو بسته شد',
    'admin.support.event.created': 'گفت‌وگو ایجاد شد',
    'admin.support.event.handoff': 'درخواست پشتیبان انسانی',
    'admin.support.event.reopened': 'گفت‌وگو دوباره باز شد',
    'admin.support.event.resolved': 'گفت‌وگو حل شد',
    'admin.support.event.titleChanged': 'عنوان تغییر کرد',
    'admin.support.inbox.allCategories': 'همه موضوع‌ها',
    'admin.support.inbox.allStatuses': 'همه وضعیت‌ها',
    'admin.support.inbox.caughtUp': 'پیام خوانده‌نشده‌ای در صف نیست.',
    'admin.support.inbox.conversations': 'گفت‌وگوها',
    'admin.support.inbox.empty': 'گفت‌وگویی برای این فیلتر وجود ندارد.',
    'admin.support.inbox.loadMore': 'گفت‌وگوهای بیشتر',
    'admin.support.inbox.noSearchResults': 'گفت‌وگویی با این جست‌وجو پیدا نشد.',
    'admin.support.inbox.search': 'جست‌وجوی عنوان، کاربر یا متن پیام',
    'admin.support.inbox.subtitle': 'پاسخ‌گویی عملیاتی به کاربران',
    'admin.support.inbox.title': 'صندوق پشتیبانی',
    'admin.support.inbox.unread': '{count} پیام خوانده‌نشده در صف است.',
    'admin.support.owner.anonymous': 'کاربر مهمان',
    'admin.support.owner.unknown': 'کاربر ناشناخته',
    'admin.support.quickReplies.add': 'پاسخ آماده جدید',
    'admin.support.quickReplies.deactivate': 'غیرفعال',
    'admin.support.quickReplies.deactivateConfirm':
        'این پاسخ از فهرست پاسخ‌های قابل استفاده حذف می‌شود.',
    'admin.support.quickReplies.deactivateTitle': 'غیرفعال‌کردن پاسخ آماده',
    'admin.support.quickReplies.edit': 'ویرایش پاسخ آماده',
    'admin.support.quickReplies.empty': 'هنوز پاسخ آماده‌ای ساخته نشده است.',
    'admin.support.quickReplies.formActive': 'فعال و قابل استفاده',
    'admin.support.quickReplies.formCategory': 'دسته‌بندی (اختیاری)',
    'admin.support.quickReplies.formContent': 'متن پاسخ',
    'admin.support.quickReplies.formOrder': 'ترتیب نمایش',
    'admin.support.quickReplies.formTitle': 'عنوان',
    'admin.support.quickReplies.inactive': 'غیرفعال',
    'admin.support.quickReplies.manageHint':
        'پاسخ‌های پرتکرار تیم را مدیریت کنید.',
    'admin.support.quickReplies.saved': 'پاسخ آماده ذخیره شد.',
    'admin.support.quickReplies.selectionHint':
        'یک پاسخ را انتخاب و پیش از ارسال ویرایش کنید.',
    'admin.support.quickReplies.title': 'پاسخ‌های آماده',
    'admin.support.quickReplies.use': 'پاسخ آماده',
    'admin.support.realtime.reconnecting': 'در حال اتصال',
    'admin.support.suggestion.generate': 'پیشنهاد پاسخ',
    'admin.support.suggestion.neverAutoSend': 'این متن خودکار ارسال نمی‌شود.',
    'admin.support.suggestion.title': 'پیشنهاد دستیار هوشمند',
    'admin.support.suggestion.useDraft': 'انتقال به ویرایشگر',
    'action.login': 'ورود',
    'action.register': 'ساخت حساب',
    'action.logout': 'خروج امن',
    'action.retry': 'تلاش دوباره',
    'action.cancel': 'انصراف',
    'action.confirm': 'تأیید',
    'action.continue': 'ادامه',
    'action.save': 'ذخیره',
    'action.refresh': 'به‌روزرسانی',
    'action.copy': 'کپی',
    'action.copied': 'کپی شد',
    'action.close': 'بستن',
    'action.send': 'ارسال',
    'action.pay': 'پرداخت',
    'action.reserve': 'رزرو سرور',
    'action.view': 'مشاهده جزئیات',
    'action.backHome': 'بازگشت به خانه',
    'common.loading': 'در حال دریافت اطلاعات…',
    'common.empty': 'هنوز چیزی اینجا نیست.',
    'common.toman': 'تومان',
    'common.hour': 'ساعت',
    'common.day': 'روز',
    'common.online': 'متصل',
    'common.offline': 'بدون اتصال',
    'home.eyebrow': 'زیرساخت محاسباتی، هر زمان که نیاز دارید',
    'home.title': 'سخت‌افزار حرفه‌ای را ساده و مطمئن رزرو کنید',
    'home.body':
        'سرور مناسب را پیدا کنید، زمان رزرو را ببینید و سرویس خود را از یک حساب امن مدیریت کنید.',
    'home.explore': 'مشاهده سرورها',
    'home.myActivity': 'فعالیت من',
    'home.available': 'سرور آماده رزرو',
    'home.reservation': 'رزرو فعال و آینده',
    'home.state.PENDING_PAYMENT': 'رزرو شما برای پرداخت آماده است',
    'home.state.ACTIVE': 'سرویس شما اکنون فعال است',
    'home.state.STARTING_SOON': 'رزرو شما به‌زودی آغاز می‌شود',
    'home.state.UPCOMING': 'رزرو آینده شما برنامه‌ریزی شده',
    'home.state.RECENT_COMPLETED': 'آخرین سرویس شما تکمیل شد',
    'home.state.DISCOVERY': 'سرور مناسب کارتان را پیدا کنید',
    'servers.title': 'انتخاب سرور',
    'servers.subtitle': 'مشخصات، ظرفیت و قیمت را مقایسه کنید.',
    'servers.search': 'جست‌وجو در CPU، GPU یا سیستم‌عامل',
    'servers.filters': 'فیلترها',
    'servers.clearFilters': 'پاک‌کردن فیلترها',
    'servers.storage': 'فضای ذخیره‌سازی',
    'servers.noResult': 'سروری با این فیلترها پیدا نشد.',
    'servers.hourly': 'ساعتی',
    'servers.daily': 'روزانه',
    'servers.available': 'آماده رزرو',
    'servers.unavailable': 'فعلاً در دسترس نیست',
    'server.specs': 'مشخصات فنی',
    'server.bestSuitedFor': 'مناسب برای',
    'reservation.title': 'رزرو سخت‌افزار',
    'reservation.start': 'شروع',
    'reservation.end': 'پایان',
    'reservation.quote': 'محاسبه قیمت',
    'reservation.available': 'این بازه در دسترس است.',
    'reservation.notAvailable': 'این بازه در دسترس نیست.',
    'reservation.total': 'مبلغ نهایی',
    'reservation.created': 'رزرو با موفقیت ثبت شد.',
    'reservation.conflict':
        'این بازه به‌تازگی رزرو شده است. زمان دیگری انتخاب کنید.',
    'reservations.title': 'رزروهای من',
    'reservations.empty': 'هنوز رزروی ثبت نکرده‌اید.',
    'services.title': 'سرویس‌های من',
    'services.empty': 'پس از پرداخت رزرو، سرویس شما اینجا نمایش داده می‌شود.',
    'services.credentials': 'اطلاعات اتصال',
    'services.sensitive':
        'این اطلاعات حساس است؛ آن را فقط در جای امن کپی کنید.',
    'payment.title': 'تأیید و پرداخت',
    'payment.pending': 'در انتظار پرداخت',
    'payment.completed': 'پرداخت تکمیل شد.',
    'profile.title': 'حساب کاربری',
    'profile.name': 'نام و نام خانوادگی',
    'profile.email': 'ایمیل',
    'profile.image': 'تغییر تصویر',
    'profile.imageTooLarge': 'تصویری کوچک‌تر از ۲ مگابایت انتخاب کنید.',
    'profile.imageUnsupported': 'یک تصویر JPG، JPEG، PNG یا WebP انتخاب کنید.',
    'profile.saved': 'اطلاعات حساب ذخیره شد.',
    'profile.language': 'زبان برنامه',
    'profile.emailChange': 'تغییر ایمیل',
    'profile.newEmail': 'ایمیل جدید',
    'profile.emailChangeHelp':
        'برای امنیت حساب، ابتدا ایمیل فعلی و سپس ایمیل جدید را با کد تأیید کنید.',
    'profile.currentVerified': 'ایمیل فعلی تأیید شد',
    'profile.newVerified': 'ایمیل جدید تأیید شد',
    'auth.welcome': 'خوش آمدید',
    'auth.loginSubtitle': 'برای مدیریت رزروها وارد حساب خود شوید.',
    'auth.identifier': 'ایمیل',
    'auth.password': 'رمز عبور',
    'auth.confirmPassword': 'تکرار رمز عبور',
    'auth.fullName': 'نام و نام خانوادگی',
    'auth.captcha': 'پاسخ {a} + {b}',
    'auth.forgot': 'رمز عبور را فراموش کرده‌اید؟',
    'auth.verifyTitle': 'تأیید ایمیل',
    'auth.verifyBody': 'کد شش‌رقمی ارسال‌شده به {email} را وارد کنید.',
    'auth.code': 'کد تأیید',
    'auth.resend': 'ارسال دوباره کد',
    'auth.forgotTitle': 'بازیابی رمز عبور',
    'auth.newPassword': 'رمز عبور جدید',
    'auth.adminRequiredTitle': 'فضای مدیریت',
    'auth.adminRequired': 'این بخش فقط برای حساب‌های مدیر در دسترس است.',
    'auth.error.invalidCredentials': 'ایمیل یا رمز عبور صحیح نیست.',
    'auth.error.emailExists': 'این ایمیل قبلاً ثبت شده است.',
    'auth.error.verificationRequired': 'پیش از ورود، ایمیل خود را تأیید کنید.',
    'auth.error.invalidCode': 'کد واردشده معتبر نیست یا منقضی شده است.',
    'auth.error.captchaExpired': 'پرسش امنیتی منقضی شده؛ دوباره تلاش کنید.',
    'auth.error.captchaIncorrect': 'پاسخ پرسش امنیتی صحیح نیست.',
    'support.title': 'پشتیبانی',
    'support.new': 'گفت‌وگوی جدید',
    'support.history': 'تاریخچه گفت‌وگوها',
    'support.empty': 'برای شروع، یک گفت‌وگوی جدید بسازید.',
    'support.category': 'موضوع گفت‌وگو',
    'support.placeholder': 'پیام خود را بنویسید…',
    'support.handoff': 'درخواست پشتیبان انسانی',
    'support.ai': 'دستیار هوشمند',
    'support.admin': 'تیم پشتیبانی',
    'support.you': 'شما',
    'support.failed': 'پیام ارسال نشد. برای تلاش دوباره لمس کنید.',
    'support.closed': 'این گفت‌وگو بسته شده و پیام جدید نمی‌پذیرد.',
    'support.resolved':
        'این گفت‌وگو حل شده است؛ با ارسال پیام دوباره باز می‌شود.',
    'support.category.general': 'پشتیبانی عمومی',
    'support.category.hardware': 'انتخاب سخت‌افزار',
    'support.category.reservations': 'رزروها',
    'support.category.payments': 'پرداخت‌ها',
    'support.category.provisioning': 'آماده‌سازی سرویس',
    'support.category.account': 'حساب کاربری',
    'support.status.aiActive': 'در حال پاسخ‌گویی AI',
    'support.status.waitingForAdmin': 'در انتظار پشتیبانی',
    'support.status.adminActive': 'پشتیبانی فعال',
    'support.status.resolved': 'حل‌شده',
    'support.status.closed': 'بسته‌شده',
    'support.status.unknown': 'وضعیت ناشناخته',
    'support.participantUnknown': 'فرستنده ناشناخته',
    'support.loadMore': 'نمایش گفت‌وگوهای بیشتر',
    'support.summary.title': 'چطور می‌توانیم کمک کنیم؟',
    'support.summary.unreadOne': '{count} پیام خوانده‌نشده دارید.',
    'support.summary.unreadMany': '{count} پیام خوانده‌نشده دارید.',
    'support.summary.description':
        'درباره سخت‌افزار، رزرو، پرداخت یا حساب خود بپرسید.',
    'support.newHelp':
        'موضوع اختیاری است. پس از ساخت گفت‌وگو، پیام خود را بنویسید.',
    'support.realtime.reconnecting': 'در حال اتصال دوباره',
    'support.realtime.reconnectingNotice':
        'در حال اتصال دوباره به به‌روزرسانی زنده…',
    'support.realtime.offlineNotice':
        'به‌روزرسانی زنده موقتاً قطع است؛ پیام‌ها همچنان ارسال می‌شوند.',
    'support.waitingNotice':
        'درخواست شما برای تیم پشتیبانی ارسال شد. می‌توانید جزئیات بیشتری اضافه کنید.',
    'support.adminNotice': 'تیم پشتیبانی در حال رسیدگی به این گفت‌وگو است.',
    'support.statusUnknownNotice':
        'وضعیت این گفت‌وگو قابل شناسایی نیست. پس از به‌روزرسانی دوباره تلاش کنید.',
    'support.messagesSemantic': 'پیام‌های گفت‌وگوی پشتیبانی',
    'support.olderLoading': 'در حال بارگذاری سابقه…',
    'support.olderMessages': 'نمایش پیام‌های قدیمی‌تر',
    'support.noMessages': 'برای آغاز این گفت‌وگو یک پیام بفرستید.',
    'support.sending': 'در حال ارسال',
    'support.aiHint':
        'ابتدا AI پاسخ می‌دهد و در صورت نیاز پشتیبانی ادامه می‌دهد.',
    'activity.title': 'فعالیت‌ها',
    'activity.description':
        'تازه‌ترین رویدادهای رزرو، پرداخت و پشتیبانی را یکجا دنبال کنید.',
    'activity.unread': '{count} خوانده‌نشده',
    'activity.unreadSemantic': 'خوانده‌نشده',
    'activity.markAll': 'همه را خوانده‌شده کن',
    'activity.markingAll': 'در حال به‌روزرسانی…',
    'activity.empty': 'هنوز فعالیتی ندارید',
    'activity.emptyBody':
        'رویدادهای رزرو، پرداخت و پشتیبانی پس از ایجاد در اینجا نمایش داده می‌شوند.',
    'activity.today': 'امروز',
    'activity.yesterday': 'دیروز',
    'activity.earlier': 'پیش‌تر',
    'activity.loadMore': 'نمایش فعالیت‌های قبلی',
    'activity.loadingMore': 'در حال بارگذاری…',
    'activity.paginationRetry': 'تلاش دوباره برای ادامه',
    'activity.system': 'سیستم',
    'activity.admin': 'مدیریت',
    'activity.sourceUnknown': 'منبع نامشخص',
    'activity.openReservation': 'مشاهده رزرو',
    'activity.openSupport': 'مشاهده گفت‌وگو',
    'activity.fallbackResource': 'سخت‌افزار شما',
    'activity.supportFallback': 'گفت‌وگوی پشتیبانی',
    'activity.unknown': 'اعلان جدید',
    'activity.type.ReservationCreated': 'رزرو {name} ثبت شد',
    'activity.type.PaymentConfirmed': 'پرداخت رزرو {name} تأیید شد',
    'activity.type.ReservationStartsSoon': 'رزرو {name} به‌زودی شروع می‌شود',
    'activity.type.ReservationStarted': 'رزرو {name} شروع شد',
    'activity.type.ReservationEndsSoon': 'سرویس {name} به‌زودی پایان می‌یابد',
    'activity.type.ReservationCompleted': 'رزرو {name} پایان یافت',
    'activity.type.ServiceDetailsAssigned':
        'اطلاعات دسترسی {name} تخصیص یافت و سرویس آماده است',
    'activity.type.SupportReply': 'تیم پشتیبانی در «{name}» پاسخ داد',
    'activity.type.AdminMessage': 'پیام مدیریت',
    'activity.type.ReservationCancelled': 'رزرو {name} توسط مدیریت لغو شد',
    'error.validation': 'اطلاعات واردشده را بررسی کنید.',
    'error.unauthorized': 'نشست شما منقضی شده است. دوباره وارد شوید.',
    'error.forbidden': 'اجازه انجام این کار را ندارید.',
    'error.offline': 'اتصال اینترنت در دسترس نیست. اطلاعات شما حفظ شده است.',
    'error.timeout': 'پاسخ سرور بیش از حد طول کشید.',
    'error.server': 'سرویس موقتاً در دسترس نیست.',
    'error.generic': 'مشکلی پیش آمد. دوباره تلاش کنید.',
  };

  static const _en = <String, String>{
    'app.name': 'HardwareReserve',
    'nav.home': 'Home',
    'nav.servers': 'Servers',
    'nav.reservations': 'Reservations',
    'nav.services': 'Services',
    'nav.profile': 'Profile',
    'nav.support': 'Support',
    'admin.entry.title': 'Admin workspace',
    'admin.entry.subtitle': 'Manage servers, reservations, users, and support',
    'admin.nav.overview': 'Overview',
    'admin.nav.servers': 'Servers',
    'admin.nav.reservations': 'Reservations',
    'admin.nav.users': 'Users',
    'admin.nav.support': 'Support',
    'admin.servers.title': 'Server management',
    'admin.servers.inventory': 'Server inventory',
    'admin.servers.search':
        'Search ID, CPU, GPU, RAM, storage, or operating system',
    'admin.servers.clearSearch': 'Clear search',
    'admin.servers.statusFilter': 'Operational status',
    'admin.servers.allStatuses': 'All statuses',
    'admin.servers.empty': 'No servers have been created yet.',
    'admin.servers.noResults': 'No server matches these filters.',
    'admin.servers.serverNumber': 'Server #{id}',
    'admin.servers.create': 'Add server',
    'admin.servers.createTitle': 'Add a server',
    'admin.servers.edit': 'Edit server',
    'admin.servers.editTitle': 'Edit server',
    'admin.servers.saveChanges': 'Save changes',
    'admin.servers.hardware': 'Hardware specifications',
    'admin.servers.storage': 'Storage',
    'admin.servers.pricing': 'Pricing',
    'admin.servers.pricingHelp':
        'Daily price must be greater than the hourly price and no more than 24 times it.',
    'admin.servers.hourlyPrice': 'Hourly price',
    'admin.servers.dailyPrice': 'Daily price',
    'admin.servers.availability': 'Availability',
    'admin.servers.activeState': 'Active server',
    'admin.servers.activeHelp':
        'Inactive servers are hidden from users and cannot receive new maintenance windows.',
    'admin.servers.active': 'Active',
    'admin.servers.inactive': 'Inactive',
    'admin.servers.status': 'Status',
    'admin.servers.finderEligible': 'Eligible for guided discovery',
    'admin.servers.finderHelp':
        'Allow this server to appear in guided hardware discovery.',
    'admin.servers.capabilities': 'Managed capabilities',
    'admin.servers.managedConfiguration': 'Managed configuration',
    'admin.servers.performanceTier': 'Performance tier',
    'admin.servers.cpuCapability': 'CPU capability',
    'admin.servers.gpuCapability': 'GPU capability',
    'admin.servers.workloadCapabilities': 'Workload capabilities',
    'admin.servers.workloadHelp':
        'Select each supported workload and its suitability from 1 to 5.',
    'admin.servers.suitability': 'Level',
    'admin.servers.noWorkloads': 'No workload capability is configured.',
    'admin.servers.yes': 'Yes',
    'admin.servers.no': 'No',
    'admin.servers.deleteTitle': 'Disable this server?',
    'admin.servers.deleteBody':
        'Server #{id} will be disabled and hidden from user discovery. Existing records are preserved.',
    'admin.servers.disable': 'Disable server',
    'admin.servers.disabled': 'Server disabled.',
    'admin.servers.notFound':
        'The server was not found. Refresh the inventory.',
    'admin.servers.verifyCreateBeforeRetry':
        'The result is uncertain. Refresh the inventory before submitting again to avoid a duplicate server.',
    'admin.servers.status.available': 'Available',
    'admin.servers.status.temporarilyUnavailable': 'Temporarily unavailable',
    'admin.servers.status.maintenance': 'Maintenance',
    'admin.servers.status.disabled': 'Disabled',
    'admin.servers.tier.entry': 'Entry',
    'admin.servers.tier.standard': 'Standard',
    'admin.servers.tier.high': 'High',
    'admin.servers.tier.extreme': 'Extreme',
    'admin.servers.workload.modelTraining': 'Model training',
    'admin.servers.workload.inference': 'Inference',
    'admin.servers.workload.rendering': 'Rendering',
    'admin.servers.workload.developmentCompilation':
        'Development and compilation',
    'admin.servers.workload.dataProcessing': 'Data processing',
    'admin.servers.workload.webBackendHosting': 'Web and backend hosting',
    'admin.servers.workload.generalCompute': 'General compute',
    'admin.servers.maintenanceTitle': 'Maintenance windows',
    'admin.servers.addMaintenance': 'Add maintenance',
    'admin.servers.createMaintenance': 'Schedule maintenance',
    'admin.servers.maintenanceHelp':
        'Choose a future interval. Times are shown locally and sent to the server as UTC.',
    'admin.servers.maintenanceReason': 'Reason (optional)',
    'admin.servers.maintenanceTimeInvalid':
        'Start must be in the future and end must be after start.',
    'admin.servers.maintenanceConflict':
        'This interval overlaps a reservation, another maintenance window, or an unavailable server.',
    'admin.servers.maintenanceCreated': 'Maintenance window scheduled.',
    'admin.servers.maintenanceRemoved': 'Maintenance window removed.',
    'admin.servers.maintenanceEmpty': 'No maintenance windows are scheduled.',
    'admin.servers.maintenanceInactiveHint':
        'New maintenance cannot be scheduled for an inactive server.',
    'admin.servers.maintenanceUpcoming': 'Upcoming',
    'admin.servers.maintenanceActive': 'In progress',
    'admin.servers.maintenanceCompleted': 'Completed',
    'admin.servers.removeMaintenance': 'Remove maintenance',
    'admin.servers.removeMaintenanceTitle': 'Remove this maintenance window?',
    'admin.servers.removeMaintenanceBody':
        'Removing it restores availability for this interval, subject to reservations and server status.',
    'admin.validation.required': 'This field is required.',
    'admin.validation.number': 'Enter a valid number.',
    'admin.validation.positive': 'Enter a number greater than zero.',
    'admin.validation.backendDetails': 'Server validation details',
    'admin.validation.max100': 'Enter no more than 100 characters.',
    'admin.dashboard.title': 'Admin overview',
    'admin.dashboard.description':
        'See operations, server capacity, and support demand at a glance.',
    'admin.dashboard.totalUsers': 'Total users',
    'admin.dashboard.totalServers': 'Total servers',
    'admin.dashboard.totalPurchases': 'Completed payments',
    'admin.dashboard.activeReservations': 'Active reservations',
    'admin.dashboard.upcomingReservations': 'Upcoming reservations',
    'admin.dashboard.startingSoon': 'Starting soon',
    'admin.dashboard.endingSoon': 'Ending soon',
    'admin.dashboard.pendingPayments': 'Pending payments',
    'admin.dashboard.unavailableServers': 'Unavailable servers',
    'admin.dashboard.maintenanceServers': 'Servers in maintenance',
    'admin.dashboard.waitingSupport': 'Waiting support',
    'admin.dashboard.operations': 'Quick access',
    'admin.dashboard.serversTitle': 'Manage servers',
    'admin.dashboard.ordersTitle': 'Reservations and orders',
    'admin.dashboard.usersTitle': 'Manage users',
    'admin.dashboard.supportTitle': 'Support inbox',
    'admin.dashboard.pendingAssignmentsBadge': 'Services needing assignment',
    'admin.dashboard.supportAttentionBadge':
        'Conversations needing Admin attention',
    'admin.dashboard.recentAudit': 'Recent Admin activity',
    'admin.pagination.previous': 'Previous page',
    'admin.pagination.next': 'Next page',
    'admin.pagination.page': 'Page {page}',
    'admin.pagination.total': 'of {count} items',
    'admin.provisioning.assigned': 'Connection details assigned',
    'admin.provisioning.notAssigned': 'Not assigned',
    'admin.reservations.title': 'Reservations and orders',
    'admin.reservations.search': 'Search',
    'admin.reservations.searchHint': 'ID, customer, email, or server',
    'admin.reservations.statusFilter': 'Reservation status',
    'admin.reservations.assignmentFilter': 'Assignment status',
    'admin.reservations.applyFilters': 'Apply filters',
    'admin.reservations.clearFilters': 'Clear filters',
    'admin.reservations.empty': 'No reservation matches these filters.',
    'admin.reservations.number': 'Reservation #{id}',
    'admin.reservations.filter.all': 'All',
    'admin.reservations.filter.pendingPayment': 'Pending payment',
    'admin.reservations.filter.active': 'Active',
    'admin.reservations.filter.upcoming': 'Upcoming',
    'admin.reservations.filter.completed': 'Completed',
    'admin.reservations.filter.cancelled': 'Cancelled',
    'admin.reservations.assignment.all': 'All',
    'admin.reservations.assignment.needsAssignment': 'Needs assignment',
    'admin.reservations.assignment.assigned': 'Assigned',
    'admin.reservationDetail.title': 'Reservation #{id}',
    'admin.reservationDetail.customer': 'Customer',
    'admin.reservationDetail.userName': 'Name',
    'admin.reservationDetail.email': 'Email',
    'admin.reservationDetail.userId': 'User ID',
    'admin.reservationDetail.openUser': 'View customer account',
    'admin.reservationDetail.hardware': 'Hardware',
    'admin.reservationDetail.serverId': 'Server ID',
    'admin.reservationDetail.storage': 'Storage',
    'admin.reservationDetail.schedulePayment': 'Schedule and payment',
    'admin.reservationDetail.start': 'Starts',
    'admin.reservationDetail.end': 'Ends',
    'admin.reservationDetail.total': 'Total',
    'admin.reservationDetail.credentials': 'Connection details',
    'admin.reservationDetail.credentialsHint':
        'Assign details only to a paid reservation. Values are not stored on this device.',
    'admin.reservationDetail.credentialsReassignHint':
        'This reservation already has connection details. Submitting replaces the current values.',
    'admin.reservationDetail.credentialsUnpaid':
        'Connection details can be assigned only after the reservation is paid.',
    'admin.reservationDetail.ip': 'IP address',
    'admin.reservationDetail.username': 'Username',
    'admin.reservationDetail.password': 'Password',
    'admin.reservationDetail.currentCredentials': 'Current service details',
    'admin.reservationDetail.revealPassword': 'Reveal password',
    'admin.reservationDetail.hidePassword': 'Hide password',
    'admin.reservationDetail.assign': 'Assign details',
    'admin.reservationDetail.assigning': 'Assigning…',
    'admin.reservationDetail.assignTitle': 'Assign connection details',
    'admin.reservationDetail.assignConfirm':
        'These details will become visible to the customer. Are you sure they are correct?',
    'admin.reservationDetail.reassign': 'Replace details',
    'admin.reservationDetail.reassignTitle': 'Replace connection details',
    'admin.reservationDetail.reassignConfirm':
        'The current details will be replaced and the customer will see only the new values. Continue?',
    'admin.reservationDetail.assignSuccess':
        'Connection details were assigned.',
    'admin.reservationDetail.cancel': 'Cancel reservation',
    'admin.reservationDetail.cancelTitle': 'Cancel this reservation?',
    'admin.reservationDetail.cancelConfirm':
        'The reservation will be cancelled and server availability will be updated.',
    'admin.reservationDetail.cancelSuccess': 'Reservation cancelled.',
    'admin.reservationDetail.cancelInvalid':
        'This reservation cannot be cancelled in its current state.',
    'admin.users.title': 'Users',
    'admin.users.search': 'Search users',
    'admin.users.searchPlaceholder': 'Name, email, or ID',
    'admin.users.clearSearch': 'Clear search',
    'admin.users.empty': 'No user was found.',
    'admin.users.accountNumber': 'Account #{id}',
    'admin.users.roleAdmin': 'Admin',
    'admin.users.roleUser': 'User',
    'admin.users.verified': 'Email verified',
    'admin.users.unverified': 'Email unverified',
    'admin.users.createTitle': 'Create an Admin account',
    'admin.users.createDescription':
        'The new account receives the same Admin role and permissions as the current Admin.',
    'admin.users.fullName': 'Full name',
    'admin.users.email': 'Email',
    'admin.users.password': 'Password',
    'admin.users.confirmPassword': 'Confirm password',
    'admin.users.passwordPolicy':
        'Password must be between 8 and 128 characters.',
    'admin.users.passwordMismatch': 'Password and confirmation do not match.',
    'admin.users.createAction': 'Create Admin',
    'admin.users.creating': 'Creating...',
    'admin.users.createSuccess': 'Admin account {email} was created.',
    'admin.userOverview.title': 'User overview',
    'admin.userOverview.userId': 'User ID',
    'admin.userOverview.createdAt': 'Account created',
    'admin.userOverview.emailVerifiedAt': 'Email verified',
    'admin.userOverview.metrics': 'Activity summary',
    'admin.userOverview.reservations': 'Total reservations',
    'admin.userOverview.active': 'Active reservations',
    'admin.userOverview.payments': 'Completed payments',
    'admin.userOverview.support': 'Support conversations',
    'admin.userOverview.unread': 'Unread notifications',
    'admin.userOverview.recentReservations': 'Recent reservations',
    'admin.userOverview.noReservations':
        'This customer does not have any reservations yet.',
    'admin.status.reservation.PendingPayment': 'Pending payment',
    'admin.status.reservation.Paid': 'Paid',
    'admin.status.reservation.Cancelled': 'Cancelled',
    'admin.status.payment.Unpaid': 'Unpaid',
    'admin.status.payment.Pending': 'Pending',
    'admin.status.payment.Completed': 'Completed',
    'admin.status.payment.Failed': 'Failed',
    'admin.status.payment.Refunded': 'Refunded',
    'admin.audit.actions.MaintenanceCreated': 'Maintenance scheduled',
    'admin.audit.actions.MaintenanceRemoved': 'Maintenance removed',
    'admin.audit.actions.ManualNotificationSent': 'Direct notification sent',
    'admin.audit.actions.BroadcastNotificationSent':
        'Broadcast notification sent',
    'admin.audit.actions.ReservationCancelled': 'Reservation cancelled',
    'admin.audit.actions.CredentialsAssigned': 'Connection details assigned',
    'admin.audit.actions.ServerCreated': 'Server created',
    'admin.audit.actions.ServerConfigurationChanged':
        'Server configuration changed',
    'admin.audit.actions.ServerDisabled': 'Server disabled',
    'admin.audit.actions.AdminAccountCreated': 'Admin account created',
    'admin.support.assignment.mine': 'Assigned to me',
    'admin.support.assignment.other': 'Assigned to another Admin',
    'admin.support.assignment.otherHint':
        'This conversation is assigned to another Admin.',
    'admin.support.conversation.aiHandoff': 'AI handoff summary',
    'admin.support.conversation.claim': 'Claim and start replying',
    'admin.support.conversation.claimBeforeReply':
        'Claim the conversation before replying.',
    'admin.support.conversation.close': 'Close conversation',
    'admin.support.conversation.closeConfirm':
        'A closed conversation no longer accepts messages.',
    'admin.support.conversation.closeTitle': 'Close conversation?',
    'admin.support.conversation.closedNotice':
        'This conversation is closed and cannot accept messages.',
    'admin.support.conversation.editTitle': 'Edit title',
    'admin.support.conversation.noMessages': 'There are no messages yet.',
    'admin.support.conversation.olderEvents': 'Older events',
    'admin.support.conversation.olderMessages': 'Older messages',
    'admin.support.conversation.resolve': 'Resolve',
    'admin.support.conversation.resolveConfirm':
        'All participants will see this as resolved.',
    'admin.support.conversation.resolveTitle': 'Mark as resolved?',
    'admin.support.conversation.resolvedNotice':
        'This conversation is resolved. Close it when appropriate.',
    'admin.support.conversation.timeline': 'Event history',
    'admin.support.conversation.title': 'Support conversation',
    'admin.support.conversation.titleField': 'Title',
    'admin.support.event.aiEscalated': 'AI escalated the conversation',
    'admin.support.event.aiFailed': 'AI processing failed',
    'admin.support.event.claimed': 'Conversation claimed',
    'admin.support.event.closed': 'Conversation closed',
    'admin.support.event.created': 'Conversation created',
    'admin.support.event.handoff': 'Human support requested',
    'admin.support.event.reopened': 'Conversation reopened',
    'admin.support.event.resolved': 'Conversation resolved',
    'admin.support.event.titleChanged': 'Title changed',
    'admin.support.inbox.allCategories': 'All categories',
    'admin.support.inbox.allStatuses': 'All statuses',
    'admin.support.inbox.caughtUp':
        'There are no unread messages in the queue.',
    'admin.support.inbox.conversations': 'Conversations',
    'admin.support.inbox.empty': 'No conversations match these filters.',
    'admin.support.inbox.loadMore': 'Load more conversations',
    'admin.support.inbox.noSearchResults':
        'No conversation matches this search.',
    'admin.support.inbox.search': 'Search title, customer, or message',
    'admin.support.inbox.subtitle': 'Operational customer support',
    'admin.support.inbox.title': 'Support inbox',
    'admin.support.inbox.unread': '{count} unread messages are waiting.',
    'admin.support.owner.anonymous': 'Guest customer',
    'admin.support.owner.unknown': 'Unknown customer',
    'admin.support.quickReplies.add': 'New quick reply',
    'admin.support.quickReplies.deactivate': 'Deactivate',
    'admin.support.quickReplies.deactivateConfirm':
        'This removes the reply from the available reply list.',
    'admin.support.quickReplies.deactivateTitle': 'Deactivate quick reply',
    'admin.support.quickReplies.edit': 'Edit quick reply',
    'admin.support.quickReplies.empty': 'No quick replies have been created.',
    'admin.support.quickReplies.formActive': 'Active and available',
    'admin.support.quickReplies.formCategory': 'Category (optional)',
    'admin.support.quickReplies.formContent': 'Reply content',
    'admin.support.quickReplies.formOrder': 'Sort order',
    'admin.support.quickReplies.formTitle': 'Title',
    'admin.support.quickReplies.inactive': 'Inactive',
    'admin.support.quickReplies.manageHint':
        'Manage the team’s reusable responses.',
    'admin.support.quickReplies.saved': 'Quick reply saved.',
    'admin.support.quickReplies.selectionHint':
        'Choose a reply, then edit it before sending.',
    'admin.support.quickReplies.title': 'Quick replies',
    'admin.support.quickReplies.use': 'Quick reply',
    'admin.support.realtime.reconnecting': 'Connecting',
    'admin.support.suggestion.generate': 'Suggest reply',
    'admin.support.suggestion.neverAutoSend':
        'This draft is never sent automatically.',
    'admin.support.suggestion.title': 'AI reply suggestion',
    'admin.support.suggestion.useDraft': 'Use as editable draft',
    'action.login': 'Sign in',
    'action.register': 'Create account',
    'action.logout': 'Secure logout',
    'action.retry': 'Try again',
    'action.cancel': 'Cancel',
    'action.confirm': 'Confirm',
    'action.continue': 'Continue',
    'action.save': 'Save',
    'action.refresh': 'Refresh',
    'action.copy': 'Copy',
    'action.copied': 'Copied',
    'action.close': 'Close',
    'action.send': 'Send',
    'action.pay': 'Pay',
    'action.reserve': 'Reserve server',
    'action.view': 'View details',
    'action.backHome': 'Back to home',
    'common.loading': 'Loading…',
    'common.empty': 'Nothing here yet.',
    'common.toman': 'Toman',
    'common.hour': 'hour',
    'common.day': 'day',
    'common.online': 'Connected',
    'common.offline': 'Offline',
    'home.eyebrow': 'Compute infrastructure, whenever you need it',
    'home.title': 'Reserve professional hardware with confidence',
    'home.body':
        'Find the right server, inspect availability, and manage service access from one secure account.',
    'home.explore': 'Explore servers',
    'home.myActivity': 'My activity',
    'home.available': 'servers ready',
    'home.reservation': 'active and upcoming',
    'home.state.PENDING_PAYMENT': 'Your reservation is ready for payment',
    'home.state.ACTIVE': 'Your service is active now',
    'home.state.STARTING_SOON': 'Your reservation starts soon',
    'home.state.UPCOMING': 'Your next reservation is scheduled',
    'home.state.RECENT_COMPLETED': 'Your latest service is complete',
    'home.state.DISCOVERY': 'Find hardware for your next workload',
    'servers.title': 'Choose a server',
    'servers.subtitle': 'Compare specifications, capacity, and pricing.',
    'servers.search': 'Search CPU, GPU, or operating system',
    'servers.filters': 'Filters',
    'servers.clearFilters': 'Clear filters',
    'servers.storage': 'Storage',
    'servers.noResult': 'No server matches these filters.',
    'servers.hourly': 'Hourly',
    'servers.daily': 'Daily',
    'servers.available': 'Available',
    'servers.unavailable': 'Unavailable',
    'server.specs': 'Technical specifications',
    'server.bestSuitedFor': 'Best suited for',
    'reservation.title': 'Reserve hardware',
    'reservation.start': 'Start',
    'reservation.end': 'End',
    'reservation.quote': 'Calculate price',
    'reservation.available': 'This time is available.',
    'reservation.notAvailable': 'This time is unavailable.',
    'reservation.total': 'Total',
    'reservation.created': 'Reservation created successfully.',
    'reservation.conflict': 'That slot was just reserved. Choose another time.',
    'reservations.title': 'My reservations',
    'reservations.empty': 'You have no reservations yet.',
    'services.title': 'My services',
    'services.empty': 'Paid reservations appear here as services.',
    'services.credentials': 'Connection details',
    'services.sensitive':
        'These details are sensitive. Copy them only to a secure destination.',
    'payment.title': 'Review and payment',
    'payment.pending': 'Payment pending',
    'payment.completed': 'Payment completed.',
    'profile.title': 'Your account',
    'profile.name': 'Full name',
    'profile.email': 'Email',
    'profile.image': 'Change photo',
    'profile.imageTooLarge': 'Choose an image smaller than 2 MB.',
    'profile.imageUnsupported': 'Choose a JPG, JPEG, PNG, or WebP image.',
    'profile.saved': 'Account details saved.',
    'profile.language': 'App language',
    'profile.emailChange': 'Change email',
    'profile.newEmail': 'New email',
    'profile.emailChangeHelp':
        'For account security, verify the current email and then the new email.',
    'profile.currentVerified': 'Current email verified',
    'profile.newVerified': 'New email verified',
    'auth.welcome': 'Welcome back',
    'auth.loginSubtitle': 'Sign in to manage your reservations.',
    'auth.identifier': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.fullName': 'Full name',
    'auth.captcha': 'Answer {a} + {b}',
    'auth.forgot': 'Forgot your password?',
    'auth.verifyTitle': 'Verify your email',
    'auth.verifyBody': 'Enter the six-digit code sent to {email}.',
    'auth.code': 'Verification code',
    'auth.resend': 'Resend code',
    'auth.forgotTitle': 'Reset your password',
    'auth.newPassword': 'New password',
    'auth.adminRequiredTitle': 'Admin workspace',
    'auth.adminRequired': 'This area is available only to Admin accounts.',
    'support.title': 'Support',
    'auth.error.invalidCredentials': 'The email or password is incorrect.',
    'auth.error.emailExists': 'An account already uses this email.',
    'auth.error.verificationRequired': 'Verify your email before signing in.',
    'auth.error.invalidCode': 'That code is invalid or expired.',
    'auth.error.captchaExpired': 'The security challenge expired. Try again.',
    'auth.error.captchaIncorrect':
        'The security challenge answer is incorrect.',
    'support.new': 'New conversation',
    'support.history': 'Conversation history',
    'support.empty': 'Create a conversation to get started.',
    'support.category': 'Conversation topic',
    'support.placeholder': 'Write a message…',
    'support.handoff': 'Request human support',
    'support.ai': 'AI assistant',
    'support.admin': 'Support Team',
    'support.you': 'You',
    'support.failed': 'Message failed. Tap to retry.',
    'support.closed':
        'This conversation is closed and cannot receive messages.',
    'support.resolved': 'This is resolved; sending a message reopens it.',
    'support.category.general': 'General support',
    'support.category.hardware': 'Hardware selection',
    'support.category.reservations': 'Reservations',
    'support.category.payments': 'Payments',
    'support.category.provisioning': 'Provisioning',
    'support.category.account': 'Account',
    'support.status.aiActive': 'AI active',
    'support.status.waitingForAdmin': 'Waiting for support',
    'support.status.adminActive': 'Support active',
    'support.status.resolved': 'Resolved',
    'support.status.closed': 'Closed',
    'support.status.unknown': 'Unknown status',
    'support.participantUnknown': 'Unknown sender',
    'support.loadMore': 'Load more conversations',
    'support.summary.title': 'How can we help?',
    'support.summary.unreadOne': '{count} unread message.',
    'support.summary.unreadMany': '{count} unread messages.',
    'support.summary.description':
        'Ask about hardware, reservations, payments, or your account.',
    'support.newHelp':
        'The topic is optional. Write your message after the conversation opens.',
    'support.realtime.reconnecting': 'Reconnecting',
    'support.realtime.reconnectingNotice': 'Reconnecting live updates…',
    'support.realtime.offlineNotice':
        'Live updates are paused; messages still send normally.',
    'support.waitingNotice':
        'Your request was sent to Support Team. You can keep adding details.',
    'support.adminNotice': 'Support Team is handling this conversation.',
    'support.statusUnknownNotice':
        'This conversation status is not recognized. Refresh and try again.',
    'support.messagesSemantic': 'Support conversation messages',
    'support.olderLoading': 'Loading history…',
    'support.olderMessages': 'Load older messages',
    'support.noMessages': 'Send a message to begin this conversation.',
    'support.sending': 'Sending',
    'support.aiHint':
        'AI responds first; Support Team can step in when needed.',
    'activity.title': 'Activity',
    'activity.description':
        'Follow reservation, payment, and support updates in one place.',
    'activity.unread': '{count} unread',
    'activity.unreadSemantic': 'Unread',
    'activity.markAll': 'Mark all as read',
    'activity.markingAll': 'Updating…',
    'activity.empty': 'No activity yet',
    'activity.emptyBody':
        'Reservation, payment, and support events will appear here as they happen.',
    'activity.today': 'Today',
    'activity.yesterday': 'Yesterday',
    'activity.earlier': 'Earlier',
    'activity.loadMore': 'Load earlier activity',
    'activity.loadingMore': 'Loading…',
    'activity.paginationRetry': 'Retry loading more',
    'activity.system': 'System',
    'activity.admin': 'Admin',
    'activity.sourceUnknown': 'Unknown source',
    'activity.openReservation': 'View reservation',
    'activity.openSupport': 'Open conversation',
    'activity.fallbackResource': 'hardware',
    'activity.supportFallback': 'support conversation',
    'activity.unknown': 'New notification',
    'activity.type.ReservationCreated': 'Your {name} reservation was created',
    'activity.type.PaymentConfirmed': 'Payment for {name} was confirmed',
    'activity.type.ReservationStartsSoon':
        'Your {name} reservation starts within 30 minutes',
    'activity.type.ReservationStarted': 'Your {name} reservation has started',
    'activity.type.ReservationEndsSoon':
        'Your {name} reservation ends within 10 minutes',
    'activity.type.ReservationCompleted': 'Your {name} reservation has ended',
    'activity.type.ServiceDetailsAssigned':
        'Access details for {name} are assigned and the service is ready',
    'activity.type.SupportReply': 'Support Team replied in “{name}”',
    'activity.type.AdminMessage': 'Message from HardwareReserve',
    'activity.type.ReservationCancelled':
        'Your {name} reservation was cancelled by an administrator',
    'error.validation': 'Check the information you entered.',
    'error.unauthorized': 'Your session expired. Sign in again.',
    'error.forbidden': 'You do not have permission to do that.',
    'error.offline': 'No internet connection. Your information is still safe.',
    'error.timeout': 'The server took too long to respond.',
    'error.server': 'The service is temporarily unavailable.',
    'error.generic': 'Something went wrong. Try again.',
  };
}

class _Delegate extends LocalizationsDelegate<AppLocalizations> {
  const _Delegate();

  @override
  bool isSupported(Locale locale) =>
      const <String>{'fa', 'en'}.contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture(AppLocalizations(locale));

  @override
  bool shouldReload(_Delegate old) => false;
}

extension LocalizationBuildContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
